import Head from "next/head";
import { Main, GridExamples, Title } from "../styles/sharedstyles";
import Page from "../components/layout/page";
import Section from "../components/layout/section";
import templateRequest from "../mock/templateRequest";

// https://m2.material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins

// https://storybook.js.org/showcase/tag/card

export default function Home() {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title> Grid Examples</Title>
        <GridExamples>
          {templateRequest.sections.map((section) => (
            <Section key={section.id} components={section.components} />
          ))}
        </GridExamples>
      </Main>
    </Page>
  );
}
